name: 'Artifact downloader'
description: 'download an artifact'
author: 'Bettermarks GmbH'
inputs:
  repo:
    description: 'The repository to download from'
  token:
    description: 'The personal access token'
  artifact_name:
    description: 'The name of the artifact'
  rename:
    description: 'An alternative name for the downloaded artifact'
  wait_seconds:
    description: 'Wait for the artifact to appear'
outputs:
  commit:
    description: 'The commit sha corresponding to the artifact'
    value: ${{ steps.main.outputs.commit }}
runs:
  using: 'composite'
  steps:
    - name: install requirements
      shell: bash
      run: pip install requests
    - name: download artifact
      id: main
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_ARTIFACT_NAME: ${{ inputs.artifact_name }}
        INPUT_RENAME: ${{ inputs.rename }}
        INPUT_REPO: ${{ inputs.repo }}
        INPUT_WAIT_SECONDS: ${{ inputs.wait_seconds }}
      run: python main.py

branding:
  color: 'yellow'
  icon: 'download'
