name: 'Copy Build Artifact'
description: 'download an artifact'
author: 'Bettermarks GmbH'
inputs:
  repo:
    description: 'The repository to download from'
  token:
    description: 'The personal access token'
  artifact_name:
    description: 'The name of the artifact'
  rename:
    description: 'An alternative name for the downloaded artifact'
  wait_seconds:
    description: 'Wait for the artifact to appear'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: 'yellow'
  icon: 'download'
